name: 'transfermarkt_datasets'
version: '1.0.0'
config-version: 2

profile: 'transfermarkt_datasets'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transfermarkt_datasets:
    +materialized: table
    +file_format: parquet
    curated:
      +materialized: incremental
      +incremental_strategy: insert_overwrite
      +file_format: parquet
      +post-hook:
        - "{{ export_table(this) }}"

vars:
  export_path: '../data/parquet'  # New variable for export path
  competition_codes: [
      'ES1', 'GB1', 'L1', 'IT1', 'FR1', 'GR1', 'PO1',
      'BE1', 'UKR1', 'BE1', 'RU1', 'DK1', 'SC1', 'TR1',
      'NL1', 'NLP', 'NLSC', 'BESC', 'DFB', 'POSU', 'POCP',
      'CGB', 'UKRP', 'RUP', 'GBCS', 'SUC', 'DFL', 'CDR',
      'RUSS', 'GRP', 'SFA', 'CIT', 'DKP', 'FRCH', 'UKRS',
      'SCI', 'CL', 'EL', 'KLUB', 'ECLQ', 'CLQ', 'ELQ', 'USC',
      'FAC',
    ]
  data_diff:
    prod_database: duck
    prod_schema: prod